In [1]:
import warnings

import pandas as pd

from configs import cfg
from data import load
from data.preprocessing import Encoders, Scalers
from eda.dengue_infection_analyser import DengueInfectionAnalyzer
from eda.dengue_infection_plot import DengueInfectionPlots
from engine.analyser import do_analysis


import numpy as np

np.seterr(all='warn')
warnings.simplefilter(action='ignore', category=FutureWarning)


from data.based.based_dataset import BasedDataset
from data.preprocessing import Encoders, Scalers
from eda.based.based_analyzer import BasedAnalyzer
from eda.based.based_plots import BasedPlot

In [2]:
def do_analysis(dataset: BasedDataset, plots: BasedPlot, analyzer: BasedAnalyzer, encoder: Encoders, scaler: Scalers):


    analyzer.description()
    # analyzer.avg_temp_c()
    # plots.corr(data=dataset.df)
    # plots.numerical_features_distribution()
    # plots.year()
    # plots.city()

In [3]:
den = load(cfg)
den.load_dataset()
den.drop_cols()
encoder = Encoders(cdg=cfg)
scaler = Scalers(cfg=cfg)
analyzer = DengueInfectionAnalyzer(dataset=den, cfg=cfg)
plots = DengueInfectionPlots(dataset=den, cfg=cfg)
do_analysis(dataset=den, analyzer=analyzer, plots=plots, encoder=encoder, scaler=scaler)

--------------- dataframe info ----------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         1205 non-null   int64
 1   weekofyear   1205 non-null   int64
 2   total_cases  1205 non-null   int64
 3   city         1205 non-null   object
 4   season       1205 non-null   int64
dtypes: int64(4), object(1)
memory usage: 47.2+ KB
None


---------- dataframe description --------------
              count         mean        std     min     25%     50%     75%  \
year         1205.0  1999.623237   4.847247  1990.0  1996.0  2001.0  2004.0
weekofyear   1205.0    27.009129  14.944162     1.0    14.0    27.0    40.0
total_cases  1205.0    26.517842  46.582143     0.0     5.0    13.0    30.0
season       1205.0     2.995021   0.070417     2.0     3.0     3.0     3.0

                max
year         2007.0
weekofyear     53.0
total_cases   461.0
season          3.0


--------------- dataframe columns -----------------
Index(['year', 'weekofyear', 'total_cases', 'city', 'season'], dtype='object')


--------------- nan Values -----------------
             Total  Percent
season           0      0.0
city             0      0.0
total_cases      0      0.0
weekofyear       0      0.0
year             0      0.0


--------------- duplicates -----------------
Total number of duplicates:  0


------ Numerical/Categorical Features ------
Numerical Features: ['year', 'weekofyear', 'total_cases', 'season']
number of Numerical Features: 4
Categorical Features: ['city']
number of Categorical Features: 1


--------------- skew & kurt -----------------
calculate skewness and kurtosis of numerical features
                  skew   skew log  skew sqrt  skew box cox         kurt  \
total_cases   5.055286  -0.124762   2.063836      -0.001903   32.700020
weekofyear   -0.048019  -1.447169  -0.570612      -0.273303   -1.182963
year         -0.407556  -0.410621  -0.409089            NaN   -0.991704
season      -14.083038 -14.083038 -14.083038            NaN  196.658375

               kurt log   kurt sqrt  kurt box cox
total_cases   -0.154602    6.760028     -0.104474
weekofyear     1.859135   -0.637544     -1.035369
year          -0.989421   -0.990566           NaN
season       196.658375  196.658375           NaN


----------------- quantiles -----------------
               0.10    0.25    0.50    0.75
year         1992.0  1996.0  2001.0  2004.0
weekofyear      6.0    14.0    27.0    40.0
total_cases     1.0     5.0    13.0    30.0
season          3.0     3.0     3.0     3.0


----------------- is target balanced? -----------------
     value  counts
0        0      88
1        6      64
2        2      54
3        7      52
4        5      51
5        3      49
6        4      44
7        1      40
8        8      37
9       11      33
10      10      30
11       9      29
12      17      29
13      13      27
14      14      26
15      18      25
16      16      24
17      12      21
18      21      19
19      23      18
20      26      18
21      30      17
22      20      17
23      25      16
24      28      16
25      22      16
26      31      15
27      15      13
28      19      12
29      29      12
30      37      12
31      33      12
32      27      11
33      24      10
34      34      10
35      38       9
36      56       9
37      35       8
38      55       7
39      40       7
40      36       6
41      32       6
42      47       6
43      42       5
44      39       5
45      43       5
46      53       5
47      46       5
48      64       4
49      75       4
50      65       4
51      70       4
52      68       4
53      67       4
54      61       4
55      60       4
56      59       4
57      71       4
58      49       4
59      48       4
60      44       4
61      73       3
62      72       3
63     140       3
64      41       3
65     127       3
66      89       3
67      50       3
68      52       3
69     112       3
70      62       3
71     129       2
72      57       2
73      82       2
74      54       2
75      51       2
76      83       2
77      76       2
78      80       2
79      45       2
80      66       2
81     102       2
82     116       2
83      84       2
84      85       2
85      91       1
86     149       1
87      74       1
88     426       1
89      63       1
90      77       1
91      78       1
92      81       1
93      90       1
94     142       1
95     141       1
96      92       1
97      99       1
98     104       1
99     108       1
100    115       1
101    126       1
102    128       1
103    131       1
104    137       1
105    119       1
106    150       1
107    288       1
108    169       1
109    410       1
110    191       1
111    256       1
112    220       1
113    181       1
114    221       1
115    204       1
116    179       1
117    202       1
118    333       1
119    263       1
120    272       1
121    302       1
122    329       1
123    154       1
124    353       1
125    359       1
126    364       1
127    381       1
128    395       1
129    461       1

/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/scipy/stats/morestats.py:906: RuntimeWarning: overflow encountered in power
  variance = np.var(data**lmb / lmb, axis=0)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:202: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:205: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:216: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1028: RuntimeWarning: overflow encountered in multiply
  adjusted3 = adjusted2 * adjusted
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1040: RuntimeWarning: overflow encountered in power
  result = (count * (count - 1) ** 0.5 / (count - 2)) * (m3 / m2 ** 1.5)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1112: RuntimeWarning: overflow encountered in square
  adjusted4 = adjusted2 ** 2
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1119: RuntimeWarning: overflow encountered in square
  denom = (count - 2) * (count - 3) * m2 ** 2

In [4]:
den.df.head()

   year  weekofyear  total_cases city  season
0  2000          26            0   iq       3
1  2000          27            0   iq       3
2  2000          28            0   iq       3
3  2000          29            0   iq       3
4  2000          30            0   iq       3

In [5]:
den.df.loc[234,['year','weekofyear','season']]

year          2005
weekofyear      53
season           3
Name: 234, dtype: object

In [6]:
den.df.columns

Index(['year', 'weekofyear', 'total_cases', 'city', 'season'], dtype='object')

In [7]:
analyzer.description()

--------------- dataframe info ----------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         1205 non-null   int64
 1   weekofyear   1205 non-null   int64
 2   total_cases  1205 non-null   int64
 3   city         1205 non-null   object
 4   season       1205 non-null   int64
dtypes: int64(4), object(1)
memory usage: 47.2+ KB
None


---------- dataframe description --------------
              count         mean        std     min     25%     50%     75%  \
year         1205.0  1999.623237   4.847247  1990.0  1996.0  2001.0  2004.0
weekofyear   1205.0    27.009129  14.944162     1.0    14.0    27.0    40.0
total_cases  1205.0    26.517842  46.582143     0.0     5.0    13.0    30.0
season       1205.0     2.995021   0.070417     2.0     3.0     3.0     3.0

                max
year         2007.0
weekofyear     53.0
total_cases   461.0
season          3.0


--------------- dataframe columns -----------------
Index(['year', 'weekofyear', 'total_cases', 'city', 'season'], dtype='object')


--------------- nan Values -----------------
             Total  Percent
season           0      0.0
city             0      0.0
total_cases      0      0.0
weekofyear       0      0.0
year             0      0.0


--------------- duplicates -----------------
Total number of duplicates:  0


------ Numerical/Categorical Features ------
Numerical Features: ['year', 'weekofyear', 'total_cases', 'season']
number of Numerical Features: 4
Categorical Features: ['city']
number of Categorical Features: 1


--------------- skew & kurt -----------------
calculate skewness and kurtosis of numerical features
                  skew   skew log  skew sqrt  skew box cox         kurt  \
total_cases   5.055286  -0.124762   2.063836      -0.001903   32.700020
weekofyear   -0.048019  -1.447169  -0.570612      -0.273303   -1.182963
year         -0.407556  -0.410621  -0.409089            NaN   -0.991704
season      -14.083038 -14.083038 -14.083038            NaN  196.658375

               kurt log   kurt sqrt  kurt box cox
total_cases   -0.154602    6.760028     -0.104474
weekofyear     1.859135   -0.637544     -1.035369
year          -0.989421   -0.990566           NaN
season       196.658375  196.658375           NaN


----------------- quantiles -----------------
               0.10    0.25    0.50    0.75
year         1992.0  1996.0  2001.0  2004.0
weekofyear      6.0    14.0    27.0    40.0
total_cases     1.0     5.0    13.0    30.0
season          3.0     3.0     3.0     3.0


----------------- is target balanced? -----------------
     value  counts
0        0      88
1        6      64
2        2      54
3        7      52
4        5      51
5        3      49
6        4      44
7        1      40
8        8      37
9       11      33
10      10      30
11       9      29
12      17      29
13      13      27
14      14      26
15      18      25
16      16      24
17      12      21
18      21      19
19      23      18
20      26      18
21      30      17
22      20      17
23      25      16
24      28      16
25      22      16
26      31      15
27      15      13
28      19      12
29      29      12
30      37      12
31      33      12
32      27      11
33      24      10
34      34      10
35      38       9
36      56       9
37      35       8
38      55       7
39      40       7
40      36       6
41      32       6
42      47       6
43      42       5
44      39       5
45      43       5
46      53       5
47      46       5
48      64       4
49      75       4
50      65       4
51      70       4
52      68       4
53      67       4
54      61       4
55      60       4
56      59       4
57      71       4
58      49       4
59      48       4
60      44       4
61      73       3
62      72       3
63     140       3
64      41       3
65     127       3
66      89       3
67      50       3
68      52       3
69     112       3
70      62       3
71     129       2
72      57       2
73      82       2
74      54       2
75      51       2
76      83       2
77      76       2
78      80       2
79      45       2
80      66       2
81     102       2
82     116       2
83      84       2
84      85       2
85      91       1
86     149       1
87      74       1
88     426       1
89      63       1
90      77       1
91      78       1
92      81       1
93      90       1
94     142       1
95     141       1
96      92       1
97      99       1
98     104       1
99     108       1
100    115       1
101    126       1
102    128       1
103    131       1
104    137       1
105    119       1
106    150       1
107    288       1
108    169       1
109    410       1
110    191       1
111    256       1
112    220       1
113    181       1
114    221       1
115    204       1
116    179       1
117    202       1
118    333       1
119    263       1
120    272       1
121    302       1
122    329       1
123    154       1
124    353       1
125    359       1
126    364       1
127    381       1
128    395       1
129    461       1

/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/scipy/stats/morestats.py:906: RuntimeWarning: overflow encountered in power
  variance = np.var(data**lmb / lmb, axis=0)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:202: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:205: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/numpy/core/_methods.py:216: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1028: RuntimeWarning: overflow encountered in multiply
  adjusted3 = adjusted2 * adjusted
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1040: RuntimeWarning: overflow encountered in power
  result = (count * (count - 1) ** 0.5 / (count - 2)) * (m3 / m2 ** 1.5)
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1112: RuntimeWarning: overflow encountered in square
  adjusted4 = adjusted2 ** 2
/home/omid/anaconda3/envs/ml/lib/python3.8/site-packages/pandas/core/nanops.py:1119: RuntimeWarning: overflow encountered in square
  denom = (count - 2) * (count - 3) * m2 ** 2

In [8]:
den.df[den.df['PERSIANN_precip_mm'].isna()].head()

KeyError: 'PERSIANN_precip_mm'

In [ ]:
import pandas as pd
den.df['week2'] = pd.to_datetime(den.df['week_start_date']).dt.weekofyear
den.df.loc[:,['week_start_date','week2']]

In [ ]:
pd.to_datetime('2005-01-01').weekofyear